[2020-05-03 22:05:32,754] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /client [GET]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py", line 19, in wrapper
    verify_jwt_in_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-05-03 22:05:32,757] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/client?", "request": null, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:10:48,974] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /client [GET]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py", line 19, in wrapper
    verify_jwt_in_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-05-03 22:10:48,975] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/client?", "request": {"username": "shofi", "password": "alta123", "status": "admin"}, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:13:05,981] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /client [GET]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py", line 19, in wrapper
    verify_jwt_in_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-05-03 22:13:05,982] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/client?", "request": {"username": "shofi", "password": "alta123", "status": "admin"}, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:15:27,873] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /client [POST]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/client/resources.py", line 57, in post
    client = Clients(data['username'], hash_pass, data['status'], salt)
  File "<string>", line 2, in __init__
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 883, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 3367, in _event_on_first_init
    configure_mappers()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 3255, in configure_mappers
    mapper._post_configure_properties()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1950, in _post_configure_properties
    prop.init()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py", line 1987, in do_init
    self._generate_backref()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py", line 2221, in _generate_backref
    % (backref_key, self, m)
sqlalchemy.exc.ArgumentError: Error creating backref 'shipping_method' on relationship 'ShippingMethods.transactions': property of that name exists on mapper 'mapped class Transactions->transaction'
[2020-05-03 22:15:27,877] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/client?", "request": {"username": "shofi", "password": "alta123", "status": "admin"}, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:17:15,503] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:78} WARNING-REQUEST_LOG	{"method": "POST", "code": "200 OK", "uri": "/client?", "request": {"username": "shofi", "password": "alta123", "status": "admin"}, "response": {"id": 1, "username": "shofi", "password": "56d6960ce708ee2c8426d0c4fe06a3c4ab49c64c33569969e69bc4b41c2e2671b8a273a22196d915c8548aff983489b0e45ec06f51de0d5c2a798a86d137ba36", "status": "admin", "created_at": "Sun, 03 May 2020 22:17:15 -0000", "updated_at": null}}
[2020-05-03 22:25:51,165] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /login [GET]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/login/__init__.py", line 29, in get
    qry_client = marshal(qry_client, Users.jwt_client_fields)
NameError: name 'Users' is not defined
[2020-05-03 22:25:51,168] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/login?username=shofi&password=alta123", "request": null, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:27:16,315] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /login [GET]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/login/__init__.py", line 29, in get
    qry_client = marshal(qry_client, Users.jwt_claim_fields)
NameError: name 'Users' is not defined
[2020-05-03 22:27:16,316] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/login?username=shofi&password=alta123", "request": null, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:27:31,831] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /login [GET]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/login/__init__.py", line 29, in get
    qry_client = marshal(qry_client, Users.jwt_claim_fields)
NameError: name 'Users' is not defined
[2020-05-03 22:27:31,834] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/login?username=shofi&password=alta123", "request": null, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:27:54,575] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /login [GET]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/login/__init__.py", line 29, in get
    qry_client = marshal(qry_client, Clients.jwt_claim_fields)
AttributeError: type object 'Clients' has no attribute 'jwt_claim_fields'
[2020-05-03 22:27:54,578] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/login?username=shofi&password=alta123", "request": null, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:28:26,077] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:78} WARNING-REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/login?username=shofi&password=alta123", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODg1MTk3MDYsIm5iZiI6MTU4ODUxOTcwNiwianRpIjoiOWQ0Mjk3MDAtYzc1OC00ODdjLTg1YzktZGM2ODJiNzdhN2JkIiwiZXhwIjoxNTg4NjA2MTA2LCJpZGVudGl0eSI6InNob2ZpIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaWQiOjEsInVzZXJuYW1lIjoic2hvZmkiLCJzdGF0dXMiOiJhZG1pbiIsImlkZW50aWZpZXIiOiJzaG9maXlhIn19.XQ78acTr8RtNWYxzLHf_IxsrUJCOiDcBiLejGuHi2F4"}}
[2020-05-03 22:35:23,856] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /shipping_method [POST]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py", line 19, in wrapper
    verify_jwt_in_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-05-03 22:35:23,859] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/shipping_method?", "request": {"courier": "JNE"}, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:36:02,539] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "POST", "code": "403 FORBIDDEN", "uri": "/shipping_method?", "request": {"courier": "JNE"}, "response": {"status": "FORBIDDEN", "message": "Admin Only!"}}
[2020-05-03 22:37:44,493] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:78} WARNING-REQUEST_LOG	{"method": "POST", "code": "200 OK", "uri": "/shipping_method?", "request": {"courier": "JNE"}, "response": {"id": 1, "courier": "JNE"}}
[2020-05-03 22:40:20,605] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:78} WARNING-REQUEST_LOG	{"method": "POST", "code": "200 OK", "uri": "/client?", "request": {"username": "oci", "password": "alta123", "status": "buyer"}, "response": {"id": 2, "username": "oci", "password": "630f679f8aeaaff59e9d7d8bc8390537dbb3c6b32c28af945eb5d3e0e35b8395918ca03cecd88feecfa096b8002497c31b05edd6341add4d0a1a3bbb43d08cc4", "status": "buyer", "created_at": "Sun, 03 May 2020 22:40:20 -0000", "updated_at": null}}
[2020-05-03 22:41:07,453] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:78} WARNING-REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/login?username=oci&password=alta123", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODg1MjA0NjcsIm5iZiI6MTU4ODUyMDQ2NywianRpIjoiMDJlNzc4MzYtNTlkNi00YjRiLTkxOGUtNWIxZmY4NjNhYWNlIiwiZXhwIjoxNTg4NjA2ODY3LCJpZGVudGl0eSI6Im9jaSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyIsInVzZXJfY2xhaW1zIjp7ImlkIjoyLCJ1c2VybmFtZSI6Im9jaSIsInN0YXR1cyI6ImJ1eWVyIiwiaWRlbnRpZmllciI6InNob2ZpeWEifX0.rpDlFmN1Qla9fa50U48mFTEufCocs-gfS9EzgZPkX_g"}}
[2020-05-03 22:45:45,581] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /customer/profile [GET]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py", line 31, in wrapper
    verify_jwt_in_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-05-03 22:45:45,584] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/customer/profile?", "request": {"name": "ocici", "email": "oci@gmail.com", "province": "jawa barat", "city": "bandung", "postal_code": "65432", "city_type": "city", "street": "jalan merdeka", "phone": "12345678", "bod": "1996-06-04"}, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:46:15,808] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "GET", "code": "403 FORBIDDEN", "uri": "/customer/profile?", "request": {"name": "ocici", "email": "oci@gmail.com", "province": "jawa barat", "city": "bandung", "postal_code": "65432", "city_type": "city", "street": "jalan merdeka", "phone": "12345678", "bod": "1996-06-04"}, "response": {"status": "FORBIDDEN", "message": "Admin Only!"}}
[2020-05-03 22:47:04,461] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:78} WARNING-REQUEST_LOG	{"method": "POST", "code": "200 OK", "uri": "/customer/profile?", "request": {"name": "ocici", "email": "oci@gmail.com", "province": "jawa barat", "city": "bandung", "postal_code": "65432", "city_type": "city", "street": "jalan merdeka", "phone": "12345678", "bod": "1996-06-04"}, "response": {"id": 1, "client_id": 2, "name": "ocici", "email": "oci@gmail.com", "province": "jawa barat", "city": "bandung", "postal_code": "65432", "city_type": "city", "street": "jalan merdeka", "phone": "12345678", "bod": "Tue, 04 Jun 1996 00:00:00 -0000", "created_at": "Sun, 03 May 2020 22:47:04 -0000", "updated_at": null}}
[2020-05-03 22:48:58,646] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:78} WARNING-REQUEST_LOG	{"method": "POST", "code": "200 OK", "uri": "/client?", "request": {"username": "bagas", "password": "alta123", "status": "seller"}, "response": {"id": 3, "username": "bagas", "password": "f700db4ecbd76c78a7901a1a6a450d9adfffd5b7eb8388a90e941a21bf070702314ac0e701c87d7b2b47e1333feb894d2996e56812944cfef61372c12d02ee66", "status": "seller", "created_at": "Sun, 03 May 2020 22:48:58 -0000", "updated_at": null}}
[2020-05-03 22:49:44,611] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:78} WARNING-REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/login?username=bagas&password=alta123", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODg1MjA5ODQsIm5iZiI6MTU4ODUyMDk4NCwianRpIjoiNGM0Y2Y1N2EtMjU3Yi00YmJlLWFjYjctMmFjOWUxZmQ4NmNkIiwiZXhwIjoxNTg4NjA3Mzg0LCJpZGVudGl0eSI6ImJhZ2FzIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaWQiOjMsInVzZXJuYW1lIjoiYmFnYXMiLCJzdGF0dXMiOiJzZWxsZXIiLCJpZGVudGlmaWVyIjoic2hvZml5YSJ9fQ.eFsqCxjpueOcuyL4EP6vDMwvHomjVIR8GIc94v7l-Xs"}}
[2020-05-03 22:52:01,778] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "POST", "code": "403 FORBIDDEN", "uri": "/customer/profile?", "request": {"name": "bagasgas", "email": "bagas@gmail.com", "province": "jawa tengah", "city": "cilacap", "postal_code": "63432", "city_type": "city", "street": "jalan pahlawan", "phone": "12345678", "bod": "1996-06-04"}, "response": {"status": "FORBIDDEN", "message": "Buyer Only!"}}
[2020-05-03 22:52:25,238] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /seller/profile [POST]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py", line 48, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/seller/resources.py", line 42, in post
    args['postal_code'], args['city_type'], args['street'], args['phone'], args['bank_account'])
TypeError: __init__() missing 1 required positional argument: 'client_id'
[2020-05-03 22:52:25,240] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/seller/profile?", "request": {"name": "bagasgas", "email": "bagas@gmail.com", "province": "jawa tengah", "city": "cilacap", "postal_code": "63432", "city_type": "city", "street": "jalan pahlawan", "phone": "12345678", "bod": "1996-06-04"}, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:52:32,866] {/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py:1892} ERROR-Exception on /seller/profile [POST]
Traceback (most recent call last):
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta16/Documents/VirtualEnv/ecommerce/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py", line 48, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/seller/resources.py", line 42, in post
    args['postal_code'], args['city_type'], args['street'], args['phone'], args['bank_account'])
TypeError: __init__() missing 1 required positional argument: 'client_id'
[2020-05-03 22:52:32,869] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:85} WARNING-REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/seller/profile?", "request": {"name": "bagasgas", "email": "bagas@gmail.com", "province": "jawa tengah", "city": "cilacap", "postal_code": "63432", "city_type": "city", "street": "jalan pahlawan", "phone": "12345678", "bod": "1996-06-04"}, "response": {"message": "Internal Server Error"}}
[2020-05-03 22:53:30,321] {/home/alta16/Documents/Portfolio-E-Commerce/shofiya/blueprints/__init__.py:78} WARNING-REQUEST_LOG	{"method": "POST", "code": "200 OK", "uri": "/seller/profile?", "request": {"name": "bagasgas", "email": "bagas@gmail.com", "province": "jawa tengah", "city": "cilacap", "postal_code": "63432", "city_type": "city", "street": "jalan pahlawan", "phone": "12345678", "bod": "1996-06-04"}, "response": {"id": 1, "client_id": 0, "name": "bagasgas", "email": "bagas@gmail.com", "province": "jawa tengah", "city": "cilacap", "postal_code": "63432", "city_type": "city", "street": "jalan pahlawan", "phone": "12345678", "bank_account": null, "created_at": "Sun, 03 May 2020 22:53:30 -0000", "updated_at": null}}
